version: '3.9'

services:
  app:
    container_name: next-app-layout-container
    tty: true
    volumes:
      - .:/app
    command: >
      sh -c "yarn install && yarn dev"
    build:
      context: .
      tags:
        - next-app--layout-image
    ports:
      - "4000:4000"
    restart: unless-stopped