version: '3'

services:
  app:
    image: next-app
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./.next:/app/.next
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
      - ./next.config.js:/app/next.config.js
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock